parameters:
    sidus_eav_model.attribute_type.default.class: Sidus\EAVModelBundle\Model\AttributeType
    sidus_eav_model.attribute_type.choice.class: Sidus\EAVModelBundle\Model\ChoiceAttributeType
    sidus_eav_model.attribute_type.relation.class: Sidus\EAVModelBundle\Model\RelationAttributeType
    sidus_eav_model.attribute_type.embed.class: Sidus\EAVModelBundle\Model\EmbedAttributeType
    sidus_eav_model.attribute_type.identifier.class: Sidus\EAVModelBundle\Model\IdentifierAttributeType

services:
    sidus_eav_model.attribute_type.string:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [string, stringValue, Symfony\Component\Form\Extension\Core\Type\TextType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.text:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [text, textValue, Symfony\Component\Form\Extension\Core\Type\TextareaType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.integer:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [integer, integerValue, Symfony\Component\Form\Extension\Core\Type\NumberType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.decimal:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [decimal, decimalValue, Symfony\Component\Form\Extension\Core\Type\NumberType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.boolean:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [boolean, boolValue, Symfony\Component\Form\Extension\Core\Type\CheckboxType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.html:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [html, textValue, Symfony\Component\Form\Extension\Core\Type\TextareaType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.date:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [date, dateValue, Symfony\Component\Form\Extension\Core\Type\DateType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.datetime:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [datetime, datetimeValue, Symfony\Component\Form\Extension\Core\Type\DateTimeType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.choice:
        class: '%sidus_eav_model.attribute_type.choice.class%' # Choice has a special class to handle multiple choices
        arguments: [choice, stringValue, Symfony\Component\Form\Extension\Core\Type\ChoiceType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.hidden:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments: [hidden, stringValue, Symfony\Component\Form\Extension\Core\Type\HiddenType]
        tags:
            - { name: sidus.attribute_type }

    # NON-STANDARD ATTRIBUTE TYPES

    sidus_eav_model.attribute_type.data:
        class: '%sidus_eav_model.attribute_type.relation.class%'
        arguments: [data, dataValue, Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.embed:
        class: '%sidus_eav_model.attribute_type.embed.class%'
        arguments: [embed, dataValue, Sidus\EAVModelBundle\Form\Type\DataType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.string_identifier:
        class: '%sidus_eav_model.attribute_type.identifier.class%'
        arguments: [string_identifier, stringIdentifier, Symfony\Component\Form\Extension\Core\Type\TextType]
        tags:
            - { name: sidus.attribute_type }

    sidus_eav_model.attribute_type.integer_identifier:
        class: '%sidus_eav_model.attribute_type.identifier.class%'
        arguments: [integer_identifier, integerIdentifier, Symfony\Component\Form\Extension\Core\Type\TextType]
        tags:
            - { name: sidus.attribute_type }
